# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestSimulPuis():
  def setup_method(self, method):
    self.driver = webdriver.Firefox(options=opts)
    #Firefox(options=opts)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testSimulPuis(self):
    self.driver.get("https://macieenligne.ci/")
    self.driver.set_window_size(1550, 838)
    self.driver.find_element(By.CSS_SELECTOR, "#particulier > h4").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cell-md-12:nth-child(3) img").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.ID, "code_tarif").click()
    dropdown = self.driver.find_element(By.ID, "code_tarif")
    dropdown.find_element(By.XPATH, "//option[. = '02 - Domestique General BT']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#code_tarif > option:nth-child(3)").click()
    self.driver.find_element(By.ID, "type_branchement").click()
    dropdown = self.driver.find_element(By.ID, "type_branchement")
    dropdown.find_element(By.XPATH, "//option[. = '1 - Monophasé']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#type_branchement > option:nth-child(2)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    '''
    self.driver.find_element(By.ID, "puissance_souscrite").click()
    dropdown = self.driver.find_element(By.ID, "puissance_souscrite")
    dropdown.find_element(By.XPATH, "//option[. = '3.3 kVA ']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#puissance_souscrite > option:nth-child(3)").click()
    self.driver.find_element(By.ID, "exploitation").click()
    dropdown = self.driver.find_element(By.ID, "exploitation")
    dropdown.find_element(By.XPATH, "//option[. = 'Abidjan, Anyama, Bingerville, Songon']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#exploitation > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "ancien_index").click()
    self.driver.find_element(By.ID, "ancien_index").send_keys("10000")
    self.driver.find_element(By.ID, "nouvel_index").click()
    self.driver.find_element(By.ID, "nouvel_index").send_keys("12000")
    self.driver.find_element(By.ID, "ancienne_date").click()
    self.driver.find_element(By.ID, "ancienne_date").send_keys("2021-02-14")
    '''
    self.driver.find_element(By.CSS_SELECTOR, ".contact100-form-btn").click()
  
